# Generated by Django 4.2 on 2026-02-26

import api.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentRecord",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models._uuid_str,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("channel_id", models.CharField(db_index=True, max_length=255)),
                ("uploaded_by", models.CharField(blank=True, default="", max_length=255)),
                ("original_filename", models.CharField(max_length=500)),
                ("file_type", models.CharField(default="image", max_length=32)),
                ("page_count", models.PositiveIntegerField(default=1)),
                ("pdf_text_layer", models.JSONField(blank=True, null=True)),
                ("image_url", models.TextField(blank=True, null=True)),
                ("image_data", models.BinaryField(blank=True, null=True)),
                ("preprocessed_data", models.BinaryField(blank=True, null=True)),
                ("thumbnail_url", models.TextField(blank=True, null=True)),
                ("width", models.PositiveIntegerField(default=0)),
                ("height", models.PositiveIntegerField(default=0)),
                (
                    "ocr_status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("processing", "processing"),
                            ("completed", "completed"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("ocr_result", models.JSONField(blank=True, null=True)),
                ("raw_ocr_text", models.TextField(blank=True, null=True)),
                ("template_id", models.CharField(blank=True, max_length=36, null=True)),
                ("preprocessing_applied", models.JSONField(blank=True, default=list)),
                ("deskew_angle", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["channel_id", "created_at"], name="api_documen_channel_4292cc_idx")],
            },
        ),
        migrations.CreateModel(
            name="TemplateRecord",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models._uuid_str,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("channel_id", models.CharField(db_index=True, max_length=255)),
                ("created_by", models.CharField(blank=True, default="", max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("thumbnail_url", models.TextField(blank=True, null=True)),
                ("thumbnail_data", models.BinaryField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("feature_keypoints", models.BinaryField(blank=True, null=True)),
                ("source_document_id", models.CharField(blank=True, max_length=36, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["channel_id", "created_at"], name="api_templat_channel_6204ea_idx")],
            },
        ),
        migrations.CreateModel(
            name="TemplateLabelRecord",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models._uuid_str,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label_type", models.CharField(default="custom", max_length=32)),
                ("label_name", models.CharField(max_length=255)),
                ("color", models.CharField(default="#FF0000", max_length=20)),
                ("relative_x", models.FloatField(default=0.0)),
                ("relative_y", models.FloatField(default=0.0)),
                ("relative_width", models.FloatField(default=0.1)),
                ("relative_height", models.FloatField(default=0.1)),
                ("expected_format", models.CharField(blank=True, max_length=255, null=True)),
                ("is_required", models.BooleanField(default=False)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="api.templaterecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BatchJobRecord",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models._uuid_str,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("channel_id", models.CharField(db_index=True, max_length=255)),
                ("created_by", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("processing", "processing"),
                            ("completed", "completed"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("document_ids", models.JSONField(blank=True, default=list)),
                ("processed_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batch_jobs",
                        to="api.templaterecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["channel_id", "created_at"], name="api_batchjo_channel_5a0091_idx")],
            },
        ),
        migrations.CreateModel(
            name="AnnotationRecord",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models._uuid_str,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label_type", models.CharField(default="custom", max_length=32)),
                ("label_name", models.CharField(blank=True, default="", max_length=255)),
                ("color", models.CharField(default="#FF0000", max_length=20)),
                ("bounding_box", models.JSONField(blank=True, null=True)),
                ("extracted_text", models.TextField(blank=True, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("valid", "valid"),
                            ("invalid", "invalid"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="api.documentrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
